refactor star file reading
gutsche-lab/peepingtom pull request #60
Opened 2020-12-13 00:15 UTC by alisterburt

Here's an attempt at refactoring star file IO into something a little more flexible, keen to hear your thoughts

The main ideas behind this implementation are that:
- main function `read_star` reads raw data using starfile then dispatches reading
- reading is attempted by explicit "reader_functions" sequentially

I think that overall this is more explicit than the use of conventions as we were working with before which quickly becomes an unreadable nested if/else mess where interpretation is mixed with parsing. The price is a little bit of code duplication, although some refactoring could be done

relion 3.1 style shifts are now handled inline, optics and particles dataframes are merged so that shifts can be calculated properly - the implementation is robust to the possibility of multiple optics groups (which can have different pixel sizes, happens in single particle sometimes)

One thing that's lost in this implementation is the ability to use your regex wizardry for filename matching, I'm sure it can be added back in I just didn't understand it enough to do so

2020-12-13 00:17 UTC, alisterburt commented
this will close #59 

should also note that tests should be added - I'll try to add the test data repo with the following tomorrow
- a dynamo table file
- a relion 3.0 star file
- a relion 3.1 star file

2020-12-13 12:13 UTC, alisterburt commented on peepingtom/io_/read/star/utils.py
> +        properties = {key: df[key].to_numpy() for key in df.columns}
should be df_[key]

2020-12-14 08:56 UTC, brisvag requested changes
I don't like this much code duplication, especially considering how the same stuff was basically written a third time in #62.

However, I really like the sub-dispatcher system. Doing something similar to what I did higher up for file extensions looks clean and makes sense.

I think maybe we should find another way of "splitting" the IO, because doing it by extension like this forces us to split things that behave effectively identically like tbl and several types of starfiles.
Maybe splitting by type of DataBlock generated? This way we could have a common `utils` function for similar things.

Either way, I still think the `conventions` dict should exist in some shape or form. Not only it makes it easier for people to add their own specific readers, so long as they are star-like (if not, wrong part of the codebase), but it allows us to maintain better and more easily add new versions and whatnot.

2020-12-14 08:56 UTC, brisvag commented on peepingtom/io_/read/star/star.py
> +    raise NotImplementedError(f'Failed to parse {star_path} using {failed_reader_functions}')
I don't think is necessarily a `NotImplementedError`. The file may be corrupt, for example. Using the more generic `ValueError` allows us to catch this higher up together with the rest of IO.

2020-12-14 17:19 UTC, alisterburt commented
@brisvag just summarising our discussion a bit here:

- we agreed that star file and dynamo table handling should not be handled by the same Handler
- dispatching data already read from disk is the right way to go within the star reading module, despite the nested-ness
- maybe handling star IO more generically is useful, given the duplication we see here

my feeling is still that I like these explicit handlings of specific cases despite the presence of common logic, it gives the function single responsibility and is nice and explicit

I think this is now ready to merge!

2020-12-15 08:57 UTC, brisvag approved these changes
Agreed, we may come back to the duplication in the future, but for now it's good to go!

2020-12-15 08:58 UTC, merged